---
- name: Install default packages to Debian systems
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
    - libpq-dev
    - python-dev
    - python2
    - python3-pip
  when: ansible_os_family == 'Debian'

- name: Install default packages to RedHat systems
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
    - python-dev
    - libpq-dev
    - python2
    - python3-pip
  when: ansible_os_family == 'RedHat'

#- name: Download script for install pip2
#  get_url:
#    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
#    dest: /etc/get-pip.py
#    mode: 0644
#
#- name: Install pip2
#  script: /etc/get-pip.py
#  args:
#    executable: python2
#
#- name: Install Python packages
#  pip: "name={{ item }}  state=present"
#  with_items:
#    - psycopg2-binary

#- name: Make sure psycopg2 is installed
#  pip:
#    name: psycopg2
#    state: present