---
- name: Install default packages to Debian systems
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
    - libpq-dev
    - python-dev
  when: ansible_os_family == 'Debian'

- name: Install default packages to RedHat systems
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
    - python-dev
    - libpq-dev
  when: ansible_os_family == 'RedHat'

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary