---
- name: Install default packages to Debian systems
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
  when: ansible_os_family == 'Debian'

- name: Install default packages to RedHat systems
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
  when: ansible_os_family == 'RedHat'
